# theme.toml template for a Hugo theme
# See https://github.com/spf13/hugoThemes#themetoml for an example

name = "Startbootstrap Business Casual"
license = "Apache 2.0"
licenselink = "https://github.com/jkinred/hugo-startbootstrap-business-casual/blob/master/LICENSE.md"
description = "Startbootstrap Business Casual theme for Hugo"
homepage = "http://siteforthistheme.com/"
tags = ["blog", "bootstrap"]
features = ["blog", "bootstrap"]
min_version = 0.14

[author]
  name = "Jonathan Kinred"
  homepage = "http://github.com/"

# If porting an existing theme
[original]
  name = "Startbootstrap Business Casual"
  homepage = "http://startbootstrap.com/template-overviews/business-casual"
  repo = "https://github.com/IronSummitMedia/startbootstrap-business-casual"
